
package com.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPersonaService", targetNamespace = "http://servicio.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPersonaService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarPersona", targetNamespace = "http://servicio.com/", className = "com.servicio.EliminarPersona")
    @ResponseWrapper(localName = "eliminarPersonaResponse", targetNamespace = "http://servicio.com/", className = "com.servicio.EliminarPersonaResponse")
    @Action(input = "http://servicio.com/IPersonaService/eliminarPersonaRequest", output = "http://servicio.com/IPersonaService/eliminarPersonaResponse")
    public void eliminarPersona(
        @WebParam(name = "arg0", targetNamespace = "")
        Persona arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.servicio.Persona>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPersonas", targetNamespace = "http://servicio.com/", className = "com.servicio.ListarPersonas")
    @ResponseWrapper(localName = "listarPersonasResponse", targetNamespace = "http://servicio.com/", className = "com.servicio.ListarPersonasResponse")
    @Action(input = "http://servicio.com/IPersonaService/listarPersonasRequest", output = "http://servicio.com/IPersonaService/listarPersonasResponse")
    public List<Persona> listarPersonas();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrarPersona", targetNamespace = "http://servicio.com/", className = "com.servicio.RegistrarPersona")
    @ResponseWrapper(localName = "registrarPersonaResponse", targetNamespace = "http://servicio.com/", className = "com.servicio.RegistrarPersonaResponse")
    @Action(input = "http://servicio.com/IPersonaService/registrarPersonaRequest", output = "http://servicio.com/IPersonaService/registrarPersonaResponse")
    public void registrarPersona(
        @WebParam(name = "arg0", targetNamespace = "")
        Persona arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.servicio.Persona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarPersonaPorId", targetNamespace = "http://servicio.com/", className = "com.servicio.EncontrarPersonaPorId")
    @ResponseWrapper(localName = "encontrarPersonaPorIdResponse", targetNamespace = "http://servicio.com/", className = "com.servicio.EncontrarPersonaPorIdResponse")
    @Action(input = "http://servicio.com/IPersonaService/encontrarPersonaPorIdRequest", output = "http://servicio.com/IPersonaService/encontrarPersonaPorIdResponse")
    public Persona encontrarPersonaPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Persona arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.servicio.Persona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encontrarPersonaPorEmail", targetNamespace = "http://servicio.com/", className = "com.servicio.EncontrarPersonaPorEmail")
    @ResponseWrapper(localName = "encontrarPersonaPorEmailResponse", targetNamespace = "http://servicio.com/", className = "com.servicio.EncontrarPersonaPorEmailResponse")
    @Action(input = "http://servicio.com/IPersonaService/encontrarPersonaPorEmailRequest", output = "http://servicio.com/IPersonaService/encontrarPersonaPorEmailResponse")
    public Persona encontrarPersonaPorEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        Persona arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modificarPersona", targetNamespace = "http://servicio.com/", className = "com.servicio.ModificarPersona")
    @ResponseWrapper(localName = "modificarPersonaResponse", targetNamespace = "http://servicio.com/", className = "com.servicio.ModificarPersonaResponse")
    @Action(input = "http://servicio.com/IPersonaService/modificarPersonaRequest", output = "http://servicio.com/IPersonaService/modificarPersonaResponse")
    public void modificarPersona(
        @WebParam(name = "arg0", targetNamespace = "")
        Persona arg0);

}
